### PR TITLE
Various fixes for macOS hosts

### PR DESCRIPTION
**Pull request by mhaeuser**
There currently are various issues with building on macOS:
- The tests fail, because unnamed POSIX semaphores are unsupported.
- Building using automake fails, because ASM preprocessor directives are not processed.
- Building using automake on Apple Silicon additionally fails, because the architecture is unsupported.

Unrelated to macOS, but tested only there:
- Building using recent autoconf fails, because deprecated constructions and macros are used.

All fixes were tested on macOS Sonoma on an M1 Pro machine, all tests executed by "make check" via automake and CMake pass.

### CODE REVIEW

**Comment by markfoodyburton** [comment]
Hi Marvin, thanks for this PR. Right now, there is a large update in preparation for SystemC 3.0 which will include fixes for MacOSX. Hopefully that will resolve this issue. In the meantime, let's leave this PR open, and if there are still problems we can re-visit?

**Comment by mhaeuser** [comment]
Sure, thanks for the update!

**Comment by maehne** [comment]
I think that this PR can be successfully closed, as https://github.com/OSCI-WG/systemc/pull/551 got merged.

**Comment by mhaeuser** [comment]
I don’t have access to that repository, so unfortunately I cannot comment. But thanks for update!

**Comment by lmailletcontoz** [comment]
Fixed in SystemC 3.0.0 release. Feel free to reopen in case of regression.

**Comment by mhaeuser** [comment]
Thanks! I *briefly* inspected the changes:
* https://github.com/accellera-official/systemc/pull/62/commits/f3c38e6846322bab4398d53387ab41290cf38b44: Not applied, the related issues remain. I basically have to run `autoupdate` before I can build.
* https://github.com/accellera-official/systemc/pull/62/commits/7751ffc85272183afa14c8503f3dc636babe2683: Applied, LGTM.
* https://github.com/accellera-official/systemc/pull/62/commits/5681208c9683c41981f946c18fc3b4bf523ee2d4: Not applied, but still works. This is because, as C++ 17 is forced now, the problematic definition is never used to begin with. However, the code for C++ pre-17 is still there (and will still break if you downgrade the C++ version). Will it be removed in the future?
* https://github.com/accellera-official/systemc/pull/62/commits/91fd0d5b49d4f633068ac3eb6465554f12da0a1e: Applied, LGMT.

I find this upstream commit a bit odd, though: https://github.com/accellera-official/systemc/commit/594a1aab19a2af3c4928ce7eabb7b58967d860bd
Why is this flag not passed to the supported compilers by configure.ac? CMake works out-of-the-box on Apple silicon, while the autotools route requires manually setting `CXXFLAGS`.

Thank you for your effort!

**Comment by maehne** [comment]
Thanks for the feedback @mhaeuser! 

@lmailletcontoz: Could you please reopen this PR, so that the two not yet applied improvements can be evaluated?

**Comment by pah** [comment]
> * https://github.com/accellera-official/systemc/commit/f3c38e6846322bab4398d53387ab41290cf38b44: Not applied, the related issues remain. I basically have to run autoupdate before I can build.
 
I only see warnings when running `config/bootstrap` with `autoconf 2.71` on my side.  Migrating the `configure.ac` to require a newer version of `autoconf` would require looking at the available versions on "old" operating systems like e.g. RedHat 7.

Users are generally assumed to run off the [`release`](https://github.com/accellera-official/systemc/tree/release) branch, which includes pre-generated Automake files.

> * https://github.com/accellera-official/systemc/commit/5681208c9683c41981f946c18fc3b4bf523ee2d4: [...] Will it be removed in the future?

Yes, pre-C++17 code will be dropped from the code base incrementally.  Building for pre-C++17 is already rejected via [`sc_cmnhdr.h`](https://github.com/accellera-official/systemc/blob/bd3b79756597f9debc5d255d3ee0fa6c70ff73d2/src/sysc/kernel/sc_cmnhdr.h#L114).

**Comment by mhaeuser** [comment]
Thanks for your insight, @pah!

> I only see warnings when running `config/bootstrap` with `autoconf 2.71` on my side. Migrating the `configure.ac` to require a newer version of `autoconf` would require looking at the available versions on "old" operating systems like e.g. RedHat 7.

Right. I'm not sure what minimum version the changes would upgrade it to, but the documentation indicates those constructs have co-existed for a while.

> Users are generally assumed to run off the [`release`](https://github.com/accellera-official/systemc/tree/release) branch, which includes pre-generated Automake files.

Ah, I hit the issues when I had to modify the autoconf files for https://github.com/accellera-official/systemc/commit/7751ffc85272183afa14c8503f3dc636babe2683, so I just re-tried the same process. The pre-generated files indeed work-as is. Thank you!

> Yes, pre-C++17 code will be dropped from the code base incrementally. Building for pre-C++17 is already rejected via [sc_cmnhdr.h](https://github.com/accellera-official/systemc/blob/bd3b79756597f9debc5d255d3ee0fa6c70ff73d2/src/sysc/kernel/sc_cmnhdr.h#L114).

Good, then I think that commit can be dropped.

As both GNU make and CMake work OOTB now, I'll close the PR again. The update to the autoconf files is mostly a matter of preference in this case.

**Pull request closed without merging**
